Create filter option
SDG-Tool-T10/SDG-Tool pull request #100
Opened 2021-05-27 10:53 UTC by koenhamstra

Alex and i create the filter option on the blog page.

Not able to run javascript in .js file. therefore js is included in html body of the index.blade.php

Filter works on SDG, Activity, Business Operation and Program.

When "None" is selected in the filter option will automatically show the name of the filter.

2021-05-27 10:57 UTC, Sanyi0001 requested changes
Pending conflict needs to be resolved

2021-05-27 11:03 UTC, awqfrxx commented on resources/js/blog.js
> +}
Why is this js code twice in the code?
Once in the public folder and once in the resource folder.
Also myFunction is bad naming for the function

2021-05-27 11:04 UTC, awqfrxx commented on resources/views/blogs/index.blade.php
> +                    <option value="{{$sdg->name}}">{{$sdg->name}}</option>
try to keep spaces between all the {{ stuff }} like this since we've been trying to do that everywhere

2021-05-27 11:05 UTC, awqfrxx commented on resources/views/blogs/index.blade.php
> +    <script>
idk about this lol ask Hao
should not be here

2021-05-27 11:06 UTC, awqfrxx commented on resources/views/common/master.blade.php
> +{{--<script src="././resources/js/blog.js"></script>--}}
remove commented out code

2021-05-27 11:06 UTC, awqfrxx commented on routes/web.php
> +//})->middleware(['auth'])->name('admin');
don't we need this anymore? then we can delete it

2021-05-27 11:07 UTC, awqfrxx requested changes
how did u come up with that js code. looks very hard 😱
gj guys

2021-05-27 11:08 UTC, awqfrxx commented on resources/views/blogs/index.blade.php
> +    <script>
you should be able to run it from the public/js folder though? and then call it from the index.blade with a @section('script')

2021-05-27 11:10 UTC, Sanyi0001 commented on resources/views/blogs/index.blade.php
> +                                    <p class="blogSDG">SDG: {{$sdg->name}}</p>
space before and after {{}}

2021-05-27 11:20 UTC, AlexGit123 commented on resources/js/blog.js
> +}
we were testing if we could get rid of the js from the HTML file.

and agreed, we missed that

2021-05-27 11:31 UTC, AlexGit123 commented on resources/views/common/master.blade.php
> +{{--<script src="././resources/js/blog.js"></script>--}}
will do

2021-05-27 11:31 UTC, AlexGit123 commented on resources/views/blogs/index.blade.php
> +    <script>
no, we had problems but we'll ask the others how to do it

2021-05-27 11:50 UTC, AnnevanHeeren commented on database/seeders/BusinessOperationSeeder.php
> +
whitespace

2021-05-27 11:51 UTC, AnnevanHeeren commented on public/css/app.css
> +
whitespace

2021-05-27 11:52 UTC, AnnevanHeeren requested changes
Requesting whitespace removal

2021-05-27 13:30 UTC, Koreyoshi159 commented on app/Http/Controllers/BlogController.php
> +
white space

2021-05-27 13:30 UTC, Koreyoshi159 commented on app/Http/Controllers/BlogController.php
> +
isn't here a white space too much ?

2021-05-27 13:31 UTC, Koreyoshi159 commented on app/Http/Controllers/ProgramController.php
> +        $this->authorize('admin-access');
what does this do

2021-05-27 13:32 UTC, Sanyi0001 approved these changes

2021-05-27 13:32 UTC, Koreyoshi159 commented on resources/views/blogs/index.blade.php
> +            @continue($blog->visibility == 0)
Do this in the controller instead of here, check the main branch for more info

2021-05-27 13:34 UTC, Koreyoshi159 commented on resources/views/blogs/index.blade.php
> +                                <p>Subgoal: {{ $blog->subSdgs }}</p>
Its business_operation right now and also sub_sdgs and this doesn't work for sub sdg because it is an array

2021-05-27 13:34 UTC, Koreyoshi159 commented on resources/views/blogs/index.blade.php
> +
white space

2021-05-27 13:35 UTC, Koreyoshi159 commented on resources/views/blogs/index.blade.php
> +    </script>
Put the script in a separate file then in the blade file

2021-05-27 13:35 UTC, Koreyoshi159 commented on resources/views/common/master.blade.php
> +
??

2021-05-27 13:35 UTC, Koreyoshi159 commented on resources/views/common/master.blade.php
> +
??

2021-05-27 13:36 UTC, Koreyoshi159 requested changes
Small changes

2021-05-28 07:33 UTC, AlexGit123 commented on resources/views/common/master.blade.php
> +
?? was the only problem whitespace?

2021-05-28 12:09 UTC, AnnevanHeeren approved these changes
Nice work!

2021-05-31 11:25 UTC, awqfrxx commented on public/js/blog.js
> +    console.log(inputArray);
we forgot to remove this i guess lol

2021-05-31 12:46 UTC, Sanyi0001 requested changes
If I select 2 filters, one that doesn't match, and after I switch to 2 matching filters it won't show up

2021-05-31 13:54 UTC, Sanyi0001 approved these changes

2021-05-31 14:07 UTC, AnnevanHeeren approved these changes
Great job!

2021-05-31 21:00 UTC, Koreyoshi159 approved these changes
Uhm nice i guess, just do not know why we need the `$this->authorize('admin-access'); `everywhere

2021-05-31 21:00 UTC, merged