Updated inputfields of blog
SDG-Tool-T10/SDG-Tool pull request #106
Opened 2021-06-01 09:36 UTC by koenhamstra

Updated the value of the inputfields.

2021-06-01 09:47 UTC, AnnevanHeeren approved these changes

2021-06-01 09:47 UTC, AnnevanHeeren commented on database/seeders/ProgramSeeder.php
>          ]);
Uhh what happened here

2021-06-01 10:12 UTC, awqfrxx approved these changes

2021-06-01 10:24 UTC, AlexGit123 commented
conflicts with the DB seeder

2021-06-01 10:25 UTC, Koreyoshi159 commented on resources/views/blogs/create.blade.php
> +                <label class="label">Programs</label>
why change it from singular to plural?

2021-06-01 10:25 UTC, AlexGit123 requested changes
conflicts with db seeder

2021-06-01 10:29 UTC, awqfrxx commented on resources/views/blogs/create.blade.php
> +                <label class="label">Programs</label>
inconsistencies with the rest, we had singular and plural mixed between every input field

2021-06-01 19:56 UTC, AnnevanHeeren commented on resources/views/blogs/create.blade.php
> +                                <option disabled selected value=""> -- Select a Activity --</option>
an activity*

2021-06-01 19:57 UTC, AnnevanHeeren commented on resources/views/blogs/create.blade.php
> +                                        {{ $business_operation   ->name }}
why space after operation  :'(

2021-06-01 19:58 UTC, AnnevanHeeren requested changes
requesting changes

2021-06-01 20:02 UTC, Sanyi0001 approved these changes

2021-06-02 13:27 UTC, koenhamstra commented on resources/views/blogs/create.blade.php
> +                                        {{ $business_operation   ->name }}
fixed it

2021-06-02 13:48 UTC, Koreyoshi159 approved these changes
nice

2021-06-02 13:48 UTC, merged