Fixed admin panel css
SDG-Tool-T10/SDG-Tool pull request #116
Opened 2021-06-08 13:44 UTC by AlexGit123

Now all buttons for the pending blogs card are visible

2021-06-08 14:26 UTC, Sanyi0001 approved these changes
Working fine :)

2021-06-08 14:53 UTC, Koreyoshi159 commented on .env.example
> -MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
Why would you remove this file ????

2021-06-08 14:53 UTC, Koreyoshi159 commented on public/js/global.js
> +
2 empty lines?

2021-06-08 18:25 UTC, AlexGit123 commented on .env.example
> -MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
because it's .env.example so I changed it to .env

2021-06-08 20:11 UTC, awqfrxx commented
maybe we should put the table headers for blogs and pending blogs above the table? so it doesn't dissapear when you scroll down?
![image](https://user-images.githubusercontent.com/70522000/121250839-7bad1880-c8a6-11eb-961a-97e15af7783b.png)

2021-06-08 20:15 UTC, awqfrxx commented on public/js/global.js
> -}
what did this do again? I forgot

2021-06-09 10:23 UTC, koenhamstra approved these changes
Looks good, and works fine

2021-06-09 10:56 UTC, AlexGit123 commented on public/js/global.js
> -}
mmmmmh, good question... maybe I'll add it back just in case, I thought it was something that I wrote b4 with Hao but I was mistaken 😓😭

2021-06-09 10:59 UTC, AlexGit123 commented on public/js/global.js
> +
lol

2021-06-09 20:28 UTC, AnnevanHeeren requested changes
Looks good, but the table headers should be sticky

2021-06-10 10:59 UTC, awqfrxx requested changes
merge conflicht because you're using the outdated code for the filters, use the one where we use the object and for each loops instead of the for loops with an array

2021-06-10 11:03 UTC, AnnevanHeeren approved these changes

2021-06-10 12:29 UTC, awqfrxx approved these changes
good work man

2021-06-10 12:29 UTC, merged