Functioning CRUD with authentication
SDG-Tool-T10/SDG-Tool pull request #44
Opened 2021-04-01 11:56 UTC by koenhamstra

Seeders are made for;
- Policy
- Sdg
- Activity

2021-04-01 15:03 UTC, Koreyoshi159 commented on database/migrations/2021_04_01_105323_create_policies_table.php
> +}
What is policies ?

2021-04-01 15:03 UTC, Koreyoshi159 commented on database/seeders/BlogSeeder.php
> +
white line ?

2021-04-01 15:04 UTC, Koreyoshi159 commented on database/seeders/SdgSeeder.php
> +
why this white space?

2021-04-01 15:05 UTC, Koreyoshi159 commented on resources/views/blog.blade.php
> +                                </select>
Education can also be a foreach

2021-04-01 15:06 UTC, Koreyoshi159 commented on routes/web.php
> +// Route::get('/blog', [BlogController::class, 'index']);
remove commented code

2021-04-01 15:07 UTC, Koreyoshi159 commented on app/Models/Blog.php
> +    protected $guarded = [];
We will have a discussion about fillable and guarded.

2021-04-01 16:42 UTC, awqfrxx commented on app/Http/Controllers/BlogController.php
> +    protected function validateBlog(){
you are already in the Blog controller so Blog is not needed here.
Change to getValidate for example?

2021-04-01 16:45 UTC, awqfrxx commented on database/migrations/2021_03_30_100707_create_blogs_table.php
> +            $table->boolean("visibility")->default(false);
I think this errors when u try to create a blog because it'll say there's no dfault value for the column visibility.
change the value 'false' into a boolean value (so 0 or 1), in this case 0

2021-04-01 16:48 UTC, awqfrxx requested changes
fix the errors and the rest looks nice!

2021-04-01 17:23 UTC, AnnevanHeeren requested changes
Requesting changes

2021-04-02 08:01 UTC, Koreyoshi159 commented on database/migrations/2021_03_30_100707_create_blogs_table.php
> +            $table->boolean("visibility")->default(false);
That is because of you have to remigrate your database xD

2021-04-02 08:04 UTC, Koreyoshi159 commented on resources/views/blog.blade.php
> +        <section class="section">
Why do you use a section inside a form?

2021-04-02 08:05 UTC, Koreyoshi159 commented on routes/web.php
>  Route::get('/blog', [BlogController::class, 'index']);
If you use a resource controller remove unused routes.

2021-04-02 08:06 UTC, Koreyoshi159 requested changes
See comments

2021-04-02 15:06 UTC, awqfrxx commented on database/migrations/2021_03_30_100707_create_blogs_table.php
> +            $table->boolean("visibility")->default(false);
> That is because of you have to remigrate your database xD

😮

2021-04-03 08:17 UTC, koenhamstra commented on database/migrations/2021_04_01_105323_create_policies_table.php
> +}
Should be "Business Processes". translated from "Bedrijfsvoering"

2021-04-03 08:22 UTC, koenhamstra commented on database/migrations/2021_04_01_105323_create_policies_table.php
> +}
I noticed BusinessProcesses are already in there. deleted the policies.

2021-04-03 08:30 UTC, koenhamstra commented on resources/views/blog.blade.php
> +                                </select>
fixed

2021-04-03 08:31 UTC, koenhamstra commented on routes/web.php
> +// Route::get('/blog', [BlogController::class, 'index']);
fixed

2021-04-03 08:31 UTC, koenhamstra commented on database/seeders/SdgSeeder.php
> +
fixed

2021-04-03 08:31 UTC, koenhamstra commented on database/seeders/BlogSeeder.php
> +
fixed

2021-04-03 08:32 UTC, koenhamstra commented on app/Http/Controllers/BlogController.php
> +    protected function validateBlog(){
Done

2021-04-03 08:41 UTC, koenhamstra commented on resources/views/blog.blade.php
> +        <section class="section">
well noticed.. fixed it

2021-04-03 08:45 UTC, koenhamstra commented
All conflicts are solved... pull request can be merged

2021-04-04 12:12 UTC, merged