Added create CRUD for research group on admin panel
SDG-Tool-T10/SDG-Tool pull request #45
Opened 2021-04-01 14:47 UTC by AlexGit123

2021-04-01 15:08 UTC, Koreyoshi159 commented on app/Http/Controllers/AdminController.php
> +
White space

2021-04-01 15:09 UTC, Koreyoshi159 commented on app/Http/Controllers/ResearchGroupController.php
> +     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
???

2021-04-01 15:09 UTC, Koreyoshi159 commented on app/Http/Controllers/ResearchGroupController.php
> +    public function store(ResearchGroup $researchGroup, Request $request)
why is there a researchGroup variable

2021-04-01 15:10 UTC, Koreyoshi159 commented on resources/views/researchGroup/create.blade.php
> +
white space

2021-04-01 15:11 UTC, Koreyoshi159 commented on resources/views/admin.blade.php
>      <div class="" style="padding: 10%">
Inline style?

2021-04-01 15:11 UTC, awqfrxx commented on resources/views/admin.blade.php
> +                    <div class="card" style="width: 500px">
inline styling here?
should remove this

2021-04-01 15:11 UTC, Koreyoshi159 commented on resources/views/admin.blade.php
>                                  <h1 style="padding-left: 50%">
Inline style

2021-04-01 15:11 UTC, awqfrxx commented on resources/views/admin.blade.php
> +                                    <h1 style="padding-left: 50%">
inline styling. remove this

2021-04-01 15:11 UTC, Koreyoshi159 commented on routes/web.php
> +
White space?

2021-04-01 15:12 UTC, awqfrxx commented on resources/views/admin.blade.php
> +                    <div class="card" style="width: 500px">
inline styling again. remove this

2021-04-01 15:12 UTC, Koreyoshi159 requested changes
Check out the comments

2021-04-01 15:12 UTC, awqfrxx commented on resources/views/admin.blade.php
> +                                    <h1 style="padding-left: 50%">
inline styling again. remove this

2021-04-01 15:15 UTC, awqfrxx requested changes
remove all the inline styling

2021-04-01 17:18 UTC, AnnevanHeeren commented on resources/views/researchGroup/create.blade.php
> +                                <p>Create!</p>
the ! doesn't look very professional, maybe remove that

2021-04-01 17:19 UTC, AnnevanHeeren requested changes
Resolve feedback

2021-04-02 07:59 UTC, Koreyoshi159 commented on app/Http/Controllers/AdminController.php
> +
Why will there be a white space between 2 variables?

2021-04-02 07:59 UTC, Koreyoshi159 commented on app/Http/Controllers/ResearchGroupController.php
> +
White space

2021-04-02 19:04 UTC, Koreyoshi159 approved these changes
Everything is good we need someone to fix the admin panel's divs xD

2021-04-02 19:15 UTC, merged