made a contact page
SDG-Tool-T10/SDG-Tool pull request #50
Opened 2021-04-22 09:43 UTC by AnnevanHeeren

Made a contact page, added it to navbar, contact page contains info about Joeri with a picture next to it

2021-04-22 09:51 UTC, awqfrxx commented on resources/views/contact.blade.php
> +
fix whitespace

2021-04-22 09:51 UTC, awqfrxx commented on resources/views/contact.blade.php
> +
fix whitespace

2021-04-22 09:57 UTC, awqfrxx commented on resources/views/contact.blade.php
> +                            <img style="height: 360px; width: 360px; margin: 10px 50px 50px 180px;" src="./image/contact.png" />
fix in-line styling

2021-04-22 09:59 UTC, awqfrxx requested changes
page looks good, just fix whitespace and in-line styling

2021-04-22 10:47 UTC, Koreyoshi159 commented on resources/views/common/master.blade.php
> +    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
Why is this in masters.blade.php you only use it on the contact page right?

2021-04-22 10:51 UTC, awqfrxx commented on resources/views/contact.blade.php
> +    <div class="columns" style="margin: 50px">
there's also inline styling here and below these as well

2021-04-22 15:26 UTC, koenhamstra approved these changes
Looks good

2021-04-23 08:54 UTC, awqfrxx approved these changes

2021-04-23 08:58 UTC, merged