changed course to program
SDG-Tool-T10/SDG-Tool pull request #53
Opened 2021-04-22 13:23 UTC by Koreyoshi159

Changed all related things to "course" into "program".
On all paged the link to courseController also to the right controller

2021-04-22 13:29 UTC, AnnevanHeeren commented on app/Http/Controllers/ProgramController.php
> +     * @param  \App\Models\Program  $program
there are 2 spaces between Program and $program

2021-04-22 13:33 UTC, AnnevanHeeren requested changes
Nice work, just one space too much

2021-04-22 15:19 UTC, awqfrxx commented on app/Models/Program.php
>      protected $guarded = [];
we still using guarded? or we changing to fillable

2021-04-22 15:22 UTC, awqfrxx approved these changes

2021-04-23 08:41 UTC, AnnevanHeeren approved these changes

2021-04-23 08:42 UTC, koenhamstra approved these changes
Looks good

2021-04-23 08:59 UTC, merged