Added log-in system (first half)
SDG-Tool-T10/SDG-Tool pull request #55
Opened 2021-04-22 15:15 UTC by awqfrxx

**Together with Koen we added:**

- Ability to log in
- Ability to log out
- Register users that are put into the database
- Hide admin panel from non-logged in users

**To-Do:**

- Make two different users because right now every logged in user is an admin and can see the panel (researcher account vs admin account)
- Email verification does not work
- 'Forgot your password' doesn't work because of the reason above
- 'Remember me' checkbox doesn't work

2021-04-22 15:21 UTC, awqfrxx commented
The in-line styling is not easy to remove because we use 3 different css files and it's hard to overwrite.
If someone has tips or knows how to feel to comment

2021-04-22 18:51 UTC, AnnevanHeeren commented on app/Http/Controllers/Auth/AuthenticatedSessionController.php
> +
whitespace

2021-04-22 18:51 UTC, AnnevanHeeren commented on app/Http/Controllers/Auth/AuthenticatedSessionController.php
> +
whitespace

2021-04-22 18:51 UTC, AnnevanHeeren commented on app/Http/Controllers/Auth/AuthenticatedSessionController.php
> +
whitespace

2021-04-22 18:52 UTC, AnnevanHeeren commented on app/Http/Controllers/Auth/EmailVerificationPromptController.php
> +                    : view('auth.verify-email');
one indent too much?

2021-04-22 18:52 UTC, AnnevanHeeren commented on app/Http/Controllers/Auth/NewPasswordController.php
> +                    ? redirect()->route('login')->with('status', __($status))
indent too much?

2021-04-22 18:53 UTC, AnnevanHeeren commented on app/Http/Controllers/Auth/PasswordResetLinkController.php
> +                            ->withErrors(['email' => __($status)]);
indenting

2021-04-22 18:53 UTC, AnnevanHeeren commented on app/Http/Requests/Auth/LoginRequest.php
> +
whitespace

2021-04-22 18:54 UTC, AnnevanHeeren commented on tests/Feature/RegistrationTest.php
> +
whitedspace

2021-04-22 18:54 UTC, AnnevanHeeren commented on tests/Feature/PasswordResetTest.php
> +
whitespace

2021-04-22 18:55 UTC, AnnevanHeeren commented on routes/auth.php
> +                ->name('logout');
indenting

2021-04-22 18:56 UTC, AnnevanHeeren commented on resources/views/welcome.blade.php
> +                    @auth()
add whitespace here or remove on 19

2021-04-22 18:57 UTC, AnnevanHeeren commented on resources/views/dashboard.blade.php
> +{{--</x-app-layout>--}}
do the comments have to be here?

2021-04-22 18:58 UTC, AnnevanHeeren commented on resources/views/auth/register.blade.php
> +                                name="password"
indenting

2021-04-22 18:58 UTC, AnnevanHeeren commented on resources/views/auth/register.blade.php
> +                                name="password_confirmation" required />
indenting

2021-04-22 18:58 UTC, AnnevanHeeren commented on resources/views/auth/register.blade.php
> +
whitespace

2021-04-22 18:58 UTC, AnnevanHeeren commented on resources/views/auth/login.blade.php
> +                                required autocomplete="current-password" />
indent

2021-04-22 18:58 UTC, avanheeren commented on resources/views/auth/login.blade.php
> +
whitespace

2021-04-22 18:58 UTC, AnnevanHeeren commented on resources/views/auth/login.blade.php
> +                {{--            </a>--}}
comments?

2021-04-22 18:59 UTC, AnnevanHeeren commented on resources/views/auth/confirm-password.blade.php
> +                                required autocomplete="current-password" />
indents

2021-04-22 18:59 UTC, AnnevanHeeren commented on resources/views/admin.blade.php
> +                                                         <a href="{{ route('research_groups.edit', $researchGroup) }}">Edit</a>
one space too much

2021-04-22 19:00 UTC, AnnevanHeeren requested changes
I can see you've been working hard, nice job, just some teeny tiny things like whitespace and indenting

2021-04-23 09:54 UTC, awqfrxx commented on app/Http/Requests/Auth/LoginRequest.php
> +
We keep it like this ,2 different classes being called

2021-04-23 10:03 UTC, awqfrxx commented on routes/auth.php
> +                ->name('logout');
I disagree, the arrows are good next to eachother

2021-04-23 10:12 UTC, Koreyoshi159 approved these changes
Its fine

2021-04-23 10:13 UTC, awqfrxx commented on app/Http/Controllers/Auth/EmailVerificationPromptController.php
> +                    : view('auth.verify-email');
no

2021-04-23 10:13 UTC, awqfrxx commented on app/Http/Controllers/Auth/NewPasswordController.php
> +                    ? redirect()->route('login')->with('status', __($status))
no

2021-04-23 10:14 UTC, awqfrxx commented on tests/Feature/PasswordResetTest.php
> +
no

2021-04-23 11:19 UTC, merged