Fixed blog issues, see description. Fixed grammar errors.
SDG-Tool-T10/SDG-Tool pull request #64
Opened 2021-04-26 15:36 UTC by Sanyi0001

Fixed grammar and spelling errors, unified every field description to start with a capital letter. Now the old values will be remembered and displayed correctly. Now the old select values will be remembered and displayed correctly. Email is verified using RFC and DNS verifications. Additionally, the selected values from the blog will be stored correctly in the corresponding variable.

2021-04-26 20:49 UTC, awqfrxx approved these changes
Very nice Sanyi.
Maybe a small thing, it might be nice to be consistent with brackets and spacing between them.
`value="{{$sdg->id}}" {{ (old('sdg') == $sdg->id ? "selected":"") }}>{{ $sdg->name }}</option>
`

2021-04-28 09:21 UTC, AnnevanHeeren approved these changes

2021-04-28 09:46 UTC, Koreyoshi159 commented on resources/views/blogs/create.blade.php
> +                                <option selected value> None</option>
what does value do here ?

2021-04-28 09:47 UTC, Koreyoshi159 commented on resources/views/blogs/create.blade.php
> +                                        value="{{$program->id}}" {{ (old('program') == $program->id ? "selected":"") }}>{{ $program->name }}</option>
maybe put an enter after the option open tag, will be easier to read

2021-04-28 09:48 UTC, Koreyoshi159 commented on resources/views/blogs/create.blade.php
> +                                <option selected value> None</option>
value?

2021-04-28 09:49 UTC, Koreyoshi159 commented on resources/views/blogs/create.blade.php
> +                                        value="{{$business_operation->id}}" {{ (old('business_operation') == $business_operation->id ? "selected":"") }}>{{ $business_operation   ->name }}</option>
after "{{" and before the "}}" there should be a space if I look to other of those blade things.

2021-04-28 09:50 UTC, Koreyoshi159 commented on resources/views/blogs/create.blade.php
> +                        <textarea class="textarea @error('impact') is-danger @enderror" name="impact" id="impact"
Do you use this id anywhere ?

2021-04-28 09:51 UTC, Koreyoshi159 requested changes
almost

2021-04-28 12:06 UTC, Sanyi0001 commented on resources/views/blogs/create.blade.php
> +                        <textarea class="textarea @error('impact') is-danger @enderror" name="impact" id="impact"
Yes

2021-04-28 12:07 UTC, Sanyi0001 commented on resources/views/blogs/create.blade.php
> +                                        value="{{$program->id}}" {{ (old('program') == $program->id ? "selected":"") }}>{{ $program->name }}</option>
Could you please clarify?

2021-04-28 12:17 UTC, Koreyoshi159 commented on resources/views/blogs/create.blade.php
> +                                        value="{{$program->id}}" {{ (old('program') == $program->id ? "selected":"") }}>{{ $program->name }}</option>
Uhm not in text xD maybe give me a call xD

2021-04-28 12:18 UTC, Koreyoshi159 commented on resources/views/blogs/create.blade.php
> +                        <textarea class="textarea @error('impact') is-danger @enderror" name="impact" id="impact"
Where xD

2021-04-28 12:34 UTC, merged