added a index page for blogs
SDG-Tool-T10/SDG-Tool pull request #91
Opened 2021-05-25 15:11 UTC by Koreyoshi159

Quick fix for separate SDG blog pages,
Added a page for all the blogs.

2021-05-25 15:29 UTC, AlexGit123 approved these changes

2021-05-25 17:47 UTC, awqfrxx commented on resources/views/sdg.blade.php
> +            @continue($blog->visibility == 0)
how does this work? the @continue

2021-05-25 17:47 UTC, awqfrxx approved these changes

2021-05-25 18:46 UTC, Koreyoshi159 commented on resources/views/sdg.blade.php
> +            @continue($blog->visibility == 0)
From what I know is If it is 0 then it goes to the next one but how it exactly works idk xD

2021-05-26 07:31 UTC, AnnevanHeeren approved these changes

2021-05-26 07:45 UTC, koenhamstra requested changes
I do not see anything in the blog page beside the text "All blogs on one page
Use the filters to search for what you want".

2021-05-26 08:08 UTC, koenhamstra approved these changes
Looks good and it works

2021-05-26 12:16 UTC, merged