admin panel additions + buttons
SDG-Tool-T10/SDG-Tool pull request #97
Opened 2021-05-26 16:45 UTC by awqfrxx

added:
able to see when the blog was created
able to see type of activity after it has been approved
fixed submit buttons so you can't spamclick and submit multiple times to the database
added 2 CRUD's ("type of activities " and  "business operations")

2021-05-26 17:31 UTC, Koreyoshi159 commented on resources/views/activities/create.blade.php
> +@section('script')
Where is your JS file? why would you add it here

2021-05-26 17:32 UTC, Koreyoshi159 commented on resources/views/admin.blade.php
> +
???

2021-05-26 17:33 UTC, Koreyoshi159 commented on resources/views/blogs/create.blade.php
> +@endsection
isn't this the same as the other one?

2021-05-26 17:33 UTC, Koreyoshi159 commented on resources/views/blogs/create.blade.php
> +                        <button class="button is-info" type="submit" value="Submit" name="myButton">
myButton? what is that Use a better name for it

2021-05-26 17:34 UTC, Koreyoshi159 commented on resources/views/businessOperations/create.blade.php
> +@endsection
same script?

2021-05-26 17:34 UTC, Koreyoshi159 commented on resources/views/programs/create.blade.php
> +@endsection
hmm

2021-05-26 17:34 UTC, Koreyoshi159 commented on resources/views/programs/create.blade.php
> +                            <button class="button is-info" type="submit" name="myButton">
button name

2021-05-26 17:35 UTC, Koreyoshi159 commented on resources/views/researchGroups/create.blade.php
> +@endsection
?????

2021-05-26 17:35 UTC, Koreyoshi159 commented on resources/views/researchGroups/create.blade.php
> +                            <button class="button is-info" type="submit" name="myButton">Create</button>
name

2021-05-26 17:35 UTC, Koreyoshi159 requested changes
See comment

2021-05-26 17:50 UTC, awqfrxx commented on resources/views/activities/create.blade.php
> +@section('script')
It was done like this somewhere else

2021-05-26 17:52 UTC, awqfrxx commented on resources/views/admin.blade.php
> +
It's better with this imo. It's hell counting all the divs otherwise, this is consistent with the sections

2021-05-26 17:52 UTC, awqfrxx commented on resources/views/blogs/create.blade.php
> +@endsection
yes

2021-05-26 17:52 UTC, awqfrxx commented on resources/views/blogs/create.blade.php
> +                        <button class="button is-info" type="submit" value="Submit" name="myButton">
ok I will change it to submitbutton

2021-05-26 17:52 UTC, awqfrxx commented on resources/views/businessOperations/create.blade.php
> +@endsection
different page same script

2021-05-26 17:52 UTC, awqfrxx commented on resources/views/programs/create.blade.php
> +@endsection
hmm

2021-05-26 17:53 UTC, awqfrxx commented on resources/views/programs/create.blade.php
> +                            <button class="button is-info" type="submit" name="myButton">
see prev

2021-05-26 17:53 UTC, awqfrxx commented on resources/views/researchGroups/create.blade.php
> +@endsection
???

2021-05-26 17:53 UTC, awqfrxx commented on resources/views/researchGroups/create.blade.php
> +                            <button class="button is-info" type="submit" name="myButton">Create</button>
yes

2021-05-26 21:07 UTC, AnnevanHeeren requested changes
Discuss small changes

2021-05-26 21:07 UTC, AnnevanHeeren commented on resources/views/admin.blade.php
> +                                    <th>Type of activity</th>
Activity without capital A

2021-05-26 21:07 UTC, AnnevanHeeren commented on resources/views/admin.blade.php
> +                                <header class="card-header-title columns">Type of Activities
With capital A?

2021-05-26 21:07 UTC, AnnevanHeeren commented on resources/views/admin.blade.php
> +                                <header class="card-header-title columns">Business Op.
Op. ? Not sure if user friendly

2021-05-26 21:07 UTC, AnnevanHeeren commented on resources/views/programs/create.blade.php
> +@endsection
Hmmm

2021-05-27 08:08 UTC, awqfrxx commented on resources/views/admin.blade.php
> +                                <header class="card-header-title columns">Business Op.
any longer and it messed with the layout of the card

2021-05-27 09:17 UTC, Sanyi0001 approved these changes
Nice work:)

2021-05-27 11:30 UTC, Koreyoshi159 commented on resources/views/admin.blade.php
> +
why an empty line ?

2021-05-27 11:31 UTC, Koreyoshi159 commented on resources/views/admin.blade.php
> +
??

2021-05-27 11:31 UTC, awqfrxx commented on resources/views/admin.blade.php
> +
because i had trouble seeing which div aligned with which, i fixed it

2021-05-27 11:31 UTC, Koreyoshi159 commented on resources/views/businessOperations/edit.blade.php
> +                            <input class="input {{$errors->has('name') ? 'is-danger' : ''}}" type="text" name="name"
spaces in {{ }}

2021-05-27 11:32 UTC, Koreyoshi159 commented on resources/views/businessOperations/edit.blade.php
> +                            <p class="help is-danger">{{$errors->first('name')}}</p>
and here

2021-05-27 11:33 UTC, Koreyoshi159 commented on resources/views/activities/edit.blade.php
> +                            <input class="input {{$errors->has('name') ? 'is-danger' : ''}}" type="text" name="name"
Spacing

2021-05-27 11:33 UTC, Koreyoshi159 commented on resources/views/activities/edit.blade.php
> +                            <p class="help is-danger">{{$errors->first('name')}}</p>
and here

2021-05-27 11:35 UTC, Koreyoshi159 approved these changes
Nice work

2021-05-27 11:43 UTC, AnnevanHeeren approved these changes

2021-05-27 11:45 UTC, merged